# -*- coding: utf-8 -*-
"""ps0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18POgJ0_uMCyElSrwtBbc_huYSBAq-qG7

**Step 1: Load Libraries in Python**

**1.1 Load Libraries in Python**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**1.2 Load Your Datasets**"""

df1 = pd.read_csv('/content/Billionaires Statistics Dataset.csv')
df2 = pd.read_csv('/content/data.csv')

"""**1.3 Explore Data**"""

#for first few rows

print(df1.head())
print(df2.head())

# for first few columns

print(df1.columns)
print(df2.columns)

"""**Step 2: Data Cleaning & Preprocessing**

**2.1 Check for Missing Values**
"""

print(df1.isnull().sum())
print(df2.isnull().sum())

"""**2.2 Drop Unnecessary Columns**"""

print(df1.columns)

df1 = df1[['rank', 'finalWorth', 'category', 'personName', 'source']]

print(df1.columns)

print(df1.isnull().sum())
print(df2.isnull().sum())

"""**Step 3: Descriptive Statistics**

**3.1 Compute Summary Statistics**
"""

print(df1.describe())
print(df2.describe())

"""**3.2 Find Top Countries with Most Billionaires**"""

# Check if 'Country' or a similar column exists in df2
print(df2.columns)

print(df1.columns.tolist())

df1.columns = df1.columns.str.strip()

print(df1.columns.tolist())
print(df2.columns.tolist())

df1 = pd.read_csv("/content/Billionaires Statistics Dataset.csv")
print(df1.head())

df1.rename(columns=lambda x: x.strip().lower(), inplace=True)

top_countries = df1['country'].value_counts().head(10)

industry_counts = df1['industries'].value_counts()
print(industry_counts)

"""**Step 4: Data Visualization**

**4.1 Plot Distribution of Billionaires by Country**
"""

plt.figure(figsize=(12,6))
sns.barplot(x=top_countries.index, y=top_countries.values)
plt.xticks(rotation=45)
plt.title("Top 10 Countries with Most Billionaires")
plt.show()

"""**4.2 Plot Industry Distribution**"""

plt.figure(figsize=(12,6))
industry_counts[:10].plot(kind='bar')
plt.title("Top 10 Industries with Most Billionaires")
plt.show()

"""**4.3 Age vs. Net Worth Scatter Plot**"""

plt.figure(figsize=(10,5))
# Assuming df1 contains 'age' and 'finalWorth' columns

# Convert column names to lowercase for consistency
df1.columns = df1.columns.str.lower()

# Use the lowercase column name 'finalworth'
sns.scatterplot(x=df1['age'], y=df1['finalworth'])
plt.title("Age vs. Net Worth of Billionaires")
plt.xlabel("Age")
plt.ylabel("Net Worth")
plt.show()

"""**Step 5: Saving my Document to Work**

**5.1 Save Processed Data**
"""

import os

# Create the directory if it doesn't exist
os.makedirs('/mnt/data', exist_ok=True)

# Now you can save the DataFrame
df1.to_csv('/mnt/data/cleaned_billionaires.csv', index=False)

from google.colab import auth
auth.authenticate_user()

!git config --global user.email "kasarlasai235@gmail.com"
!git config --global user.name "SaiAnirudh659"

!git clone https://github.com/SaiAnirudh659/Vis

!mv /mnt/data/ps0.ipynb https://github.com/SaiAnirudh659/Vis/

!ls /mnt/data/