# -*- coding: utf-8 -*-
"""ps1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzHviRZVnr8exnvyQ-Yj9BztVgFajMic

**Step 1: Research Questions & Hypotheses -> ✅ Done (PDF Generated)**

**Step 2: Data Preparation (Cleaning & Standardizing) -> ✅ Done (As Code)**

**Step 3: Merging Datasets (At least 2 merges) -> ✅ Done (WHO + World Bank, then merged with NASA)**

**Step 4: Data Analysis & Visualization -> ✅ Done (Summary Stats, Correlation, 3 Visualizations)**

**Use of Data Transformations -> ✅ Done (Renaming, Replacing, Keeping/Dropping, Aggregations)**

**Final Merged Dataset Created -> ✅ Done (Final_Merged_Dataset.csv)**

---

**Step 1: Define Research Questions and Hypotheses**

-> Attached a PDF File

**Step 2: Identify Common Variables for Merging**
"""

import pandas as pd

# Load the datasets
who_air_pollution_path = "/content/WHO_Air_Pollution_Data.xlsx"
nasa_temperature_path = "/content/NASA_Temperature_Anomalies_Cleaned.csv"
world_bank_gdp_path = "/content/World_Bank_GDP_Cleaned.csv"

# Read WHO Air Pollution Data
df_air_pollution = pd.read_excel(who_air_pollution_path)
df_air_pollution_cleaned = df_air_pollution[["DIM_GEO_NAME", "DIM_TIME_YEAR", "VALUE_NUMERIC"]].copy()
df_air_pollution_cleaned.columns = ["Country", "Year", "PM2.5_Level"]
df_air_pollution_cleaned["Year"] = df_air_pollution_cleaned["Year"].astype(int)  # Ensure Year is integer

# Read NASA Temperature Anomalies Data
df_nasa_cleaned = pd.read_csv(nasa_temperature_path)
df_nasa_cleaned = df_nasa_cleaned[["Year", "Temperature_Anomaly"]].copy()
df_nasa_cleaned["Year"] = df_nasa_cleaned["Year"].astype(int)  # Ensure Year is integer

# Read World Bank GDP Data
df_gdp_cleaned = pd.read_csv(world_bank_gdp_path)
df_gdp_cleaned = df_gdp_cleaned.melt(id_vars=["Country Name", "Country Code"], var_name="Year", value_name="GDP")
df_gdp_cleaned.columns = ["Country", "Country_Code", "Year", "GDP"]
df_gdp_cleaned["Year"] = df_gdp_cleaned["Year"].astype(int)  # Ensure Year is integer

# Display cleaned datasets
print("WHO Air Pollution Data (Cleaned):")
print(df_air_pollution_cleaned.head())

print("\nNASA Temperature Anomalies Data (Cleaned):")
print(df_nasa_cleaned.head())

print("\nWorld Bank GDP Data (Cleaned):")
print(df_gdp_cleaned.head())

# Save the cleaned files for further processing
df_air_pollution_cleaned.to_csv("WHO_Air_Pollution_Cleaned.csv", index=False)
df_nasa_cleaned.to_csv("NASA_Temperature_Anomalies_Cleaned.csv", index=False)
df_gdp_cleaned.to_csv("World_Bank_GDP_Cleaned.csv", index=False)

"""**Step 3: Prepare Data for Merging & Performing Data Merging**"""

import pandas as pd

# Load the cleaned datasets
who_air_pollution_path = "/content/WHO_Air_Pollution_Cleaned.csv"
nasa_temperature_path = "/content/NASA_Temperature_Anomalies_Cleaned.csv"
world_bank_gdp_path = "/content/World_Bank_GDP_Cleaned.csv"

df_air_pollution_cleaned = pd.read_csv(who_air_pollution_path)
df_nasa_cleaned = pd.read_csv(nasa_temperature_path)
df_gdp_cleaned = pd.read_csv(world_bank_gdp_path)

# Merge WHO Air Pollution Data with World Bank GDP Data on Country and Year
merged_data = pd.merge(df_air_pollution_cleaned, df_gdp_cleaned, on=["Country", "Year"], how="inner")

# Merge the above result with NASA Temperature Anomalies Data on Year
final_merged_data = pd.merge(merged_data, df_nasa_cleaned, on="Year", how="inner")

# Display the first few rows of the merged dataset
print("Final Merged Dataset:")
print(final_merged_data.head())

# Save the merged dataset
final_merged_data.to_csv("Final_Merged_Dataset.csv", index=False)

print("\nMerged dataset saved as 'Final_Merged_Dataset.csv'")

"""**Step 4: Data Analysis and Visualization**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the merged dataset
df_merged = pd.read_csv("/content/Final_Merged_Dataset.csv")

# Scatter Plot: PM2.5 Levels vs GDP
plt.figure(figsize=(8, 6))
sns.scatterplot(x=df_merged["PM2.5_Level"], y=df_merged["GDP"])
plt.xlabel("PM2.5 Levels")
plt.ylabel("GDP (in USD)")
plt.title("Scatter Plot: PM2.5 Levels vs GDP")
plt.grid(True)
plt.show()

# Line Chart: Global Temperature Anomalies over Time
plt.figure(figsize=(10, 5))
sns.lineplot(x=df_merged["Year"], y=df_merged["Temperature_Anomaly"], marker="o")
plt.xlabel("Year")
plt.ylabel("Temperature Anomaly")
plt.title("Global Temperature Anomalies Over Time")
plt.grid(True)
plt.show()

# Bar Chart: Average PM2.5 Levels by Country (Top 10 Countries)
top_countries = df_merged.groupby("Country")["PM2.5_Level"].mean().nlargest(10)
plt.figure(figsize=(10, 5))
sns.barplot(x=top_countries.index, y=top_countries.values)
plt.xticks(rotation=45)
plt.xlabel("Country")
plt.ylabel("Average PM2.5 Levels")
plt.title("Top 10 Countries with Highest PM2.5 Levels")
plt.show()